export const DEPARTMENTS = [
  {
    id: "medical",
    nameEn: "Medical",
    nameMr: "वैद्यकीय",
    titleEn: "Medical Operations",
    titleMr: "वैद्यकीय ऑपरेशन्स",
    subtitleEn: "Emergency drug supply, cold-chain monitoring & dispatch schedules",
    subtitleMr: "तातडीचा औषध पुरवठा, कोल्ड-चेन नियंत्रण आणि वितरण वेळापत्रक",
    countdown: {
      headingEn: "NEXT DISPATCH REVIEW",
      headingMr: "पुढील डिस्पॅच आढावा",
    },
    contacts: [
      {
        roleEn: "Supply Operations Lead",
        roleMr: "पुरवठा ऑपरेशन्स प्रमुख",
        descEn: "For urgent medicine supply needs",
        descMr: "औषध पुरवठ्याच्या तातडीच्या गरजांसाठी",
        ext: "Ext. 201",
        statusType: "available",
      },
      {
        roleEn: "Cold-Chain Support",
        roleMr: "कोल्ड-चेन मदत कक्ष",
        descEn: "System and temperature alerts",
        descMr: "तापमान आणि साठवणूक समस्यांसाठी",
        ext: "Ext. 114",
        statusType: "available",
      },
      {
        roleEn: "Quality & Compliance Desk",
        roleMr: "गुणवत्ता आणि अनुपालन डेस्क",
        descEn: "Policy and approval exceptions",
        descMr: "धोरण आणि मंजुरी अपवादांसाठी",
        ext: "Ext. 305",
        statusType: "onCall",
      },
    ],
    items: [
      {
        id: 1,
        priority: "HIGH",
        titleEn: "Urgent Medicine Replenishment — ICU Stock",
        titleMr: "तातडीचा औषध पुरवठा — आयसीयू स्टॉक",
        contextEn: "Critical shortage of cardiac medicines in ICU; delivery expected from central warehouse by 10:30 AM.",
        contextMr: "आयसीयूमध्ये हृदयविकाराच्या औषधांचा तुटवडा; मध्यवर्ती गोदामातून सकाळी १०:३० पर्यंत डिलिव्हरी अपेक्षित.",
      },
      {
        id: 2,
        priority: "HIGH",
        titleEn: "Vaccine Cold-Chain Shipment — Zone A",
        titleMr: "लस कोल्ड-चेन वाहतूक — झोन ए",
        contextEn: "Temperature alert on storage unit during transport. Needs immediate rerouting to backup facility.",
        contextMr: "वाहतुकीदरम्यान साठवणूक केंद्रात तापमानाचा इशारा. पर्यायी केंद्राकडे त्वरित वळवणे आवश्यक.",
      },
      {
        id: 3,
        priority: "MEDIUM",
        titleEn: "Hospital Supply Dispatch — District General Hospital",
        titleMr: "रुग्णालय पुरवठा वितरण — जिल्हा सामान्य रुग्णालय",
        contextEn: "Bulk surgical items ready for dispatch. Waiting for final load clearance approval.",
        contextMr: "शस्त्रक्रियेच्या साहित्याची मोठी बॅच वितरणासाठी तयार. अंतिम लोडिंग मंजुरीची प्रतीक्षा.",
      },
      {
        id: 4,
        priority: "MEDIUM",
        titleEn: "Medicine Stock Transfer — Sub-center B",
        titleMr: "औषध साठा वर्ग करणे — उपकेंद्र बी",
        contextEn: "Request to transfer surplus insulin doses to primary health center suffering from high demand.",
        contextMr: "जास्त मागणी असलेल्या प्राथमिक आरोग्य केंद्रात अतिरिक्त इन्सुलिन साठा वर्ग करण्याची विनंती.",
      },
      {
        id: 5,
        priority: "LOW",
        titleEn: "Supplier Delivery Delay — Alpha Labs",
        titleMr: "पुरवठादार वितरण विलंब — अल्फा लॅब्स",
        contextEn: "Routine antibiotics shipment delayed by 24 hours. Inventory levels sufficient for current week.",
        contextMr: "नेहमीच्या अँटीबायोटिक्सचा पुरवठा २४ तास उशिराने होणार. या आठवड्यासाठी पुरेशा साठा उपलब्ध.",
      },
    ],
    anomalies: [
      {
        id: 1,
        severity: "HIGH",
        titleEn: "Cold Storage Temp Alert — Room 3",
        titleMr: "कोल्ड स्टोरेज तापमान इशारा — रूम ३",
        explanationEn: "Temperature rose to 7.2°C, exceeding safety limit of 4.0°C. Risk to stored vaccines.",
        explanationMr: "तापमान ७.२°C वर पोहोचले, जे ४.०°C च्या मर्यादेपेक्षा जास्त आहे. लसींच्या साठवणुकीला धोका.",
        detectedAtEn: "08:14 AM",
        detectedAtMr: "सकाळी ०८:१४",
      },
      {
        id: 2,
        severity: "HIGH",
        titleEn: "Rapid Stock Depletion — Insulin",
        titleMr: "जलद औषध साठा घट — इन्सुलिन",
        explanationEn: "Insulin stock decreased by 40% in last 30 mins due to emergency bulk orders from Sub-center B.",
        explanationMr: "उपकेंद्र बी कडून तातडीच्या मागणीमुळे गेल्या ३० मिनिटांत इन्सुलिन साठा ४०% कमी झाला.",
        detectedAtEn: "08:27 AM",
        detectedAtMr: "सकाळी ०८:२७",
      },
      {
        id: 3,
        severity: "MEDIUM",
        titleEn: "Dispatch Backlog — Pharmacy Hub",
        titleMr: "वैद्यकीय वितरण प्रलंबितता — फार्मसी हब",
        explanationEn: "45 urgent medicine parcels waiting to be loaded. Inflow exceeds handling capacity.",
        explanationMr: "४५ तातडीची औषधांची पार्सल लोड होण्याची वाट पाहत आहेत. काम हाताळणी क्षमतेपेक्षा जास्त.",
        detectedAtEn: "07:55 AM",
        detectedAtMr: "सकाळी ०७:५५",
      },
      {
        id: 4,
        severity: "MEDIUM",
        titleEn: "Delivery Delay — City Hospital",
        titleMr: "डिव्हरी विलंब — सिटी हॉस्पिटल",
        explanationEn: "Supply truck delayed on outer ring road by 40 mins. Estimated delivery now 10:15 AM.",
        explanationMr: "पुरवठा ट्रक आउटर ring road वर ४० मिनिटे उशिराने. सुधारित वितरण वेळ सकाळी १०:१५ वाजता.",
        detectedAtEn: "07:30 AM",
        detectedAtMr: "सकाळी ०७:३०",
      },
      {
        id: 5,
        severity: "LOW",
        titleEn: "Inventory Mismatch — Ward 5",
        titleMr: "इन्व्हेंटरी तफावत — वॉर्ड ५",
        explanationEn: "Physical count shows 3 missing boxes of surgical gloves compared to system records.",
        explanationMr: "प्रत्यक्ष मोजणीत सिस्टम रेकॉर्डच्या तुलनेत सर्जिकल ग्लोव्हजचे ३ बॉक्स कमी आढळले आहेत.",
        detectedAtEn: "07:02 AM",
        detectedAtMr: "सकाळी ०७:०२",
      },
    ],
  },
  {
    id: "logistics",
    nameEn: "Logistics",
    nameMr: "लॉजिस्टिक",
    titleEn: "Logistics Operations",
    titleMr: "लॉजिस्टिक ऑपरेशन्स",
    subtitleEn: "Fleet dispatch schedules, route tracking & cargo processing",
    subtitleMr: "वाहन ताफा वितरण वेळापत्रक, मार्ग ट्रॅकिंग आणि माल प्रक्रिया",
    countdown: {
      headingEn: "NEXT ROUTE REVIEW",
      headingMr: "पुढील मार्ग आढावा",
    },
    contacts: [
      {
        roleEn: "Dispatch Lead",
        roleMr: "वितरण प्रमुख",
        descEn: "For urgent delivery updates",
        descMr: "तातडीच्या वितरण अपडेटसाठी",
        ext: "Ext. 201",
        statusType: "available",
      },
      {
        roleEn: "Fleet Support",
        roleMr: "वाहन ताफा मदत कक्ष",
        descEn: "Vehicle and fuel tracking issues",
        descMr: "वाहन आणि इंधन ट्रॅकिंग समस्या",
        ext: "Ext. 114",
        statusType: "available",
      },
      {
        roleEn: "Warehouse Coordinator",
        roleMr: "वेअरहाऊस समन्वयक",
        descEn: "Dispatch queue clearance",
        descMr: "वितरण रांग क्लिअरन्स",
        ext: "Ext. 305",
        statusType: "onCall",
      },
    ],
    items: [
      {
        id: 1,
        priority: "HIGH",
        titleEn: "Delayed Shipment Alert — Route 4",
        titleMr: "विलंब झालेली वाहतूक — मार्ग क्र. ४",
        contextEn: "Expressway traffic blockage. Truck carrying perishable goods delayed by over 3 hours.",
        contextMr: "एक्सप्रेसवेवर वाहतूक कोंडी. नाशवंत माल घेऊन जाणारा ट्रक ३ तासांपेक्षा जास्त वेळ अडकला.",
      },
      {
        id: 2,
        priority: "HIGH",
        titleEn: "Vehicle Allocation — Backup Fleet",
        titleMr: "वाहन वाटप — पर्यायी ताफा",
        contextEn: "2 secondary trucks required for morning distribution route due to primary engine failures.",
        contextMr: "मुख्य वाहनाचे इंजिन बिघडल्यामुळे सकाळी वितरणासाठी २ अतिरिक्त वाहने आवश्यक.",
      },
      {
        id: 3,
        priority: "MEDIUM",
        titleEn: "Warehouse Dispatch Queue — Hub 1",
        titleMr: "वेअरहाऊस माल पाठवणी रांग — हब १",
        contextEn: "Inflow of local cargo is exceeding packing capacity. 15 consignments pending dispatch approval.",
        contextMr: "येणारा स्थानिक माल पॅकिंग क्षमतेपेक्षा जास्त. १५ वस्तू पाठवण्यासाठी मंजुरीच्या प्रतीक्षेत.",
      },
      {
        id: 4,
        priority: "MEDIUM",
        titleEn: "Emergency Route Change — Coastal Highway",
        titleMr: "आणीबाणी मार्ग बदल — कोस्टल हायवे",
        contextEn: "High tide warning. Route diverted via state highway, increasing transit time by 45 mins.",
        contextMr: "भरतीचा इशारा. राज्य महामार्गाने वाहतूक वळवली, प्रवासाचा वेळ ४५ मिनिटांनी वाढला.",
      },
      {
        id: 5,
        priority: "LOW",
        titleEn: "Delivery Prioritisation — Retail Center C",
        titleMr: "वितरण प्राधान्यक्रम — रिटेल सेंटर सी",
        contextEn: "Request to prioritize retail deliveries over scheduled weekly warehouse replenishment.",
        contextMr: "नियोजित साप्ताहिक वेअरहाऊस पुरवठ्यापेक्षा किरकोळ वितरणाला प्राधान्य देण्याची विनंती.",
      },
    ],
    anomalies: [
      {
        id: 1,
        severity: "HIGH",
        titleEn: "Route Delay — Expressway Hub",
        titleMr: "मार्ग विलंब — एक्सप्रेसवे हब",
        explanationEn: "Expressway transit times increased by 80 mins due to minor landslide at km 45.",
        explanationMr: "किलोमीटर ४५ जवळील दरड कोसळल्यामुळे एक्सप्रेसवेवरील प्रवासाचा वेळ ८० मिनिटांनी वाढला.",
        detectedAtEn: "08:14 AM",
        detectedAtMr: "सकाळी ०८:१४",
      },
      {
        id: 2,
        severity: "HIGH",
        titleEn: "Fuel Consumption Alert — Truck 12",
        titleMr: "इंधन वापर इशारा — ट्रक १२",
        explanationEn: "Fuel consumption rate increased by 25% over the past 50 km. Engine diagnostic recommended.",
        explanationMr: "गेल्या ५० किमीमध्ये इंधनाचा वापर २५% वाढला आहे. इंजिन तपासणीची शिफारस.",
        detectedAtEn: "08:27 AM",
        detectedAtMr: "सकाळी ०८:२७",
      },
      {
        id: 3,
        severity: "MEDIUM",
        titleEn: "Warehouse Backlog — Sector C",
        titleMr: "वेअरहाऊस बॅकलॉग — सेक्टर सी",
        explanationEn: "110 pallets of general goods pending dispatch. Packing area is operating at maximum capacity.",
        explanationMr: "११० पॅलेट मालाचे वितरण प्रलंबित. पॅकिंग क्षेत्र कमाल क्षमतेने सुरू आहे.",
        detectedAtEn: "07:55 AM",
        detectedAtMr: "सकाळी ०७:५५",
      },
      {
        id: 4,
        severity: "MEDIUM",
        titleEn: "Vehicle Downtime — Dispatch Bay",
        titleMr: "वाहन निष्क्रिय वेळ — डिस्पॅच बे",
        explanationEn: "Two primary delivery trucks scheduled for dispatch are inactive due to electrical system faults.",
        explanationMr: "वितरणासाठी नियोजित दोन मुख्य ट्रक इलेक्ट्रिकल बिघाडामुळे बंद आहेत.",
        detectedAtEn: "07:30 AM",
        detectedAtMr: "सकाळी ०७:३०",
      },
      {
        id: 5,
        severity: "LOW",
        titleEn: "Unsuccessful Deliveries Rise",
        titleMr: "वितरण अपयशात वाढ",
        explanationEn: "Failed retail delivery attempts rose by 4% today, mainly due to receiver unavailability.",
        explanationMr: "आज किरकोळ वितरणाचे अपयशी प्रयत्न ४% वाढले, प्रामुख्याने ग्राहक उपलब्ध नसल्यामुळे.",
        detectedAtEn: "07:02 AM",
        detectedAtMr: "सकाळी ०७:०२",
      },
    ],
  },
  {
    id: "mechanical",
    nameEn: "Mechanical",
    nameMr: "यांत्रिक",
    titleEn: "Mechanical Operations",
    titleMr: "यांत्रिक ऑपरेशन्स",
    subtitleEn: "Machinery status, maintenance workflows & technician assignments",
    subtitleMr: "मशिनरी स्थिती, देखभाल कामकाज आणि तंत्रज्ञ नियुक्त्या",
    countdown: {
      headingEn: "NEXT MAINTENANCE REVIEW",
      headingMr: "पुढील देखभाल आढावा",
    },
    contacts: [
      {
        roleEn: "Maintenance Lead",
        roleMr: "देखभाल प्रमुख",
        descEn: "For machine failure reports",
        descMr: "मशीन बिघाड अहवालासाठी",
        ext: "Ext. 201",
        statusType: "available",
      },
      {
        roleEn: "Technical Support",
        roleMr: "तांत्रिक मदत कक्ष",
        descEn: "Spare parts access issues",
        descMr: "स्पेअर पार्ट्स मिळवण्याच्या समस्या",
        ext: "Ext. 114",
        statusType: "available",
      },
      {
        roleEn: "Safety Inspection Desk",
        roleMr: "सुरक्षा तपासणी डेस्क",
        descEn: "Safety clearance checks",
        descMr: "सुरक्षा मंजुरी तपासणीसाठी",
        ext: "Ext. 305",
        statusType: "onCall",
      },
    ],
    items: [
      {
        id: 1,
        priority: "HIGH",
        titleEn: "Equipment Breakdown — Assembly Line 2",
        titleMr: "उपकरण बिघाड — असैम्ब्ली लाईन २",
        contextEn: "Hydraulic press pressure failure. Production stopped until maintenance technician resolves.",
        contextMr: "हायड्रॉलिक प्रेस प्रेशर बिघाड. देखभाल तंत्रज्ञ दुरुस्त करेपर्यंत उत्पादन थांबवले.",
      },
      {
        id: 2,
        priority: "HIGH",
        titleEn: "Preventive Maintenance Approval — Turbine B",
        titleMr: "प्रतिबंधात्मक देखभाल मंजुरी — टर्बाइन बी",
        contextEn: "Annual routine maintenance window starts tomorrow. Approval needed to shift power loads.",
        contextMr: "वार्षिक नियमित देखभाल उद्यापासून सुरू होत आहे. विजेचा लोड वळवण्यासाठी मंजुरी आवश्यक.",
      },
      {
        id: 3,
        priority: "MEDIUM",
        titleEn: "Spare-Parts Request — Warehouse Conveyor",
        titleMr: "स्पेअर-पार्ट्स मागणी — वेअरहाऊस कन्व्हेयर",
        contextEn: "Roller bearing replacement parts requested from regional stores. Urgent approval required.",
        contextMr: "प्रादेशिक स्टोअरमधून रोलर बेअरिंगचे सुटे भाग मागवले. तातडीची मंजुरी आवश्यक.",
      },
      {
        id: 4,
        priority: "MEDIUM",
        titleEn: "Machinery Inspection — Boiler Room 4",
        titleMr: "मशिनरी तपासणी — बॉयलर रूम ४",
        contextEn: "Semi-annual pressure vessel safety inspection due today. Inspector arriving at 11:30 AM.",
        contextMr: "सहामाही प्रेशर वेसल सुरक्षा तपासणी आज होणार. निरीक्षक सकाळी ११:३० वाजता येणार.",
      },
      {
        id: 5,
        priority: "LOW",
        titleEn: "Technician Assignment — Generator Room",
        titleMr: "तंत्रज्ञ नियुक्ती — जनरेटर रूम",
        contextEn: "Assign junior technician for routine fuel tank filter cleaning session this afternoon.",
        contextMr: "आज दुपारी इंधन टाकीच्या फिल्टरच्या नियमित स्वच्छतेसाठी कनिष्ठ तंत्रज्ञाची नियुक्ती करणे.",
      },
    ],
    anomalies: [
      {
        id: 1,
        severity: "HIGH",
        titleEn: "Vibration Alert — Compressor 4",
        titleMr: "असामान्य कंपन इशारा — कॉम्प्रेसर ४",
        explanationEn: "Vibration levels crossed 8.5 mm/s. Bearing damage suspected. Shutdown recommended.",
        explanationMr: "कंपनाची पातळी ८.५ मिमी/सेकंद पार झाली. बेअरिंग खराब झाल्याची शक्यता. बंद करण्याची शिफारस.",
        detectedAtEn: "08:14 AM",
        detectedAtMr: "सकाळी ०८:१४",
      },
      {
        id: 2,
        severity: "HIGH",
        titleEn: "Overheating Alert — Engine Room 2",
        titleMr: "ओव्हरहीटिंग इशारा — इंजिन रूम २",
        explanationEn: "Main cooling water outlet temperature reached 92°C. Safety shutdown threshold is 95°C.",
        explanationMr: "कूलिंग वॉटर आउटलेटचे तापमान ९२°C वर पोहोचले. सुरक्षेची मर्यादा ९५°C आहे.",
        detectedAtEn: "08:27 AM",
        detectedAtMr: "सकाळी ०८:२७",
      },
      {
        id: 3,
        severity: "MEDIUM",
        titleEn: "Stoppage Spike — Packaging Unit",
        titleMr: "वारंवार मशीन बंद पडणे — पॅकेजिंग युनिट",
        explanationEn: "Conveyor belt tripped 6 times in the last hour. Sensor misalignment detected.",
        explanationMr: "गेल्या तासात कन्व्हेयर बेल्ट ६ वेळा बंद पडला. सेन्सर संरेखन चुकल्याचे आढळले.",
        detectedAtEn: "07:55 AM",
        detectedAtMr: "सकाळी ०७:५५",
      },
      {
        id: 4,
        severity: "MEDIUM",
        titleEn: "Maintenance Overdue — Crane 1",
        titleMr: "देखभाल थकीत — क्रेन १",
        explanationEn: "Scheduled monthly structural inspection is overdue by 14 days. Operating license expires in 3 days.",
        explanationMr: "नियोजित मासिक संरचनात्मक तपासणी १४ दिवस थकीत. परवान्याची मुदत ३ दिवसांत संपणार आहे.",
        detectedAtEn: "07:30 AM",
        detectedAtMr: "सकाळी ०७:३०",
      },
      {
        id: 5,
        severity: "LOW",
        titleEn: "Low Stock — Hydraulic Seals",
        titleMr: "स्पेअर-पार्ट्स तुटवडा — हायड्रॉलिक सील",
        explanationEn: "Stock level of 24mm seals has fallen below minimum reorder level of 5 units.",
        explanationMr: "२४ मिमी सीलचा साठा ५ युनिट्सच्या किमान पुनर्रचना पातळीपेक्षा कमी झाला आहे.",
        detectedAtEn: "07:02 AM",
        detectedAtMr: "सकाळी ०७:०२",
      },
    ],
  },
  {
    id: "civil",
    nameEn: "Civil Services",
    nameMr: "नागरी सेवा",
    titleEn: "Civil Services Operations",
    titleMr: "नागरी सेवा ऑपरेशन्स",
    subtitleEn: "Road maintenance, drainage blockages & public work approvals",
    subtitleMr: "रस्ते देखभाल, ड्रेनेज ब्लॉकेज आणि सार्वजनिक कामांची मंजुरी",
    countdown: {
      headingEn: "NEXT FIELD REVIEW",
      headingMr: "पुढील क्षेत्र आढावा",
    },
    contacts: [
      {
        roleEn: "Ward Operations Lead",
        roleMr: "वॉर्ड ऑपरेशन्स प्रमुख",
        descEn: "For ward repair issues",
        descMr: "वॉर्ड दुरुस्ती कामांच्या समस्यांसाठी",
        ext: "Ext. 201",
        statusType: "available",
      },
      {
        roleEn: "Field Engineering Desk",
        roleMr: "क्षेत्रीय अभियांत्रिकी डेस्क",
        descEn: "Site quality inspections",
        descMr: "गुणवत्ता आणि साइट तपासणीसाठी",
        ext: "Ext. 114",
        statusType: "available",
      },
      {
        roleEn: "Contractor Coordination Desk",
        roleMr: "कंत्राटदार समन्वय डेस्क",
        descEn: "Contractor work clearances",
        descMr: "कंत्राटदाराच्या काम मंजुरीसाठी",
        ext: "Ext. 305",
        statusType: "onCall",
      },
    ],
    items: [
      {
        id: 1,
        priority: "HIGH",
        titleEn: "Urgent Pothole Repair — Ward 12",
        titleMr: "तातडीची खड्डे दुरुस्ती — वॉर्ड १२",
        contextEn: "Critical pothole reports near school junction. Repair team scheduled for 9:45 AM dispatch.",
        contextMr: "शाळेजवळील चौकात मोठ्या खड्ड्यांची तक्रार. दुरुस्ती पथक सकाळी ९:४५ वाजता रवाना होणार.",
      },
      {
        id: 2,
        priority: "HIGH",
        titleEn: "Road Resurfacing Approval — Main Market Road",
        titleMr: "रस्ता डांबरीकरण मंजुरी — मुख्य बाजार रस्ता",
        contextEn: "Overlay work complete. Awaiting final supervisor signature for opening lane to commercial vehicles.",
        contextMr: "रस्ता दुरुस्तीचे काम पूर्ण. व्यावसायिक वाहनांसाठी रस्ता खुला करण्यासाठी पर्यवेक्षकाच्या अंतिम स्वाक्षरीची प्रतीक्षा.",
      },
      {
        id: 3,
        priority: "MEDIUM",
        titleEn: "Drainage Blockage Clearance — Sector 4",
        titleMr: "ड्रेनेज ब्लॉकेज स्वच्छता — सेक्टर ४",
        contextEn: "Blocked storm drain causing local waterlogging. Sanitation crew deployed to clear trash.",
        contextMr: "साचलेल्या पाण्याच्या निचऱ्यासाठी बंद पडलेली गटारे. कचरा काढण्यासाठी स्वच्छता पथक तैनात.",
      },
      {
        id: 4,
        priority: "MEDIUM",
        titleEn: "Contractor Work Inspection — Bridge Approach Road",
        titleMr: "कंत्राटदार काम तपासणी — पूल जोडरस्ता",
        contextEn: "Quality inspection scheduled for new asphalt layer. Compliance checking required before next payment.",
        contextMr: "नवीन डांबरी थराची गुणवत्ता तपासणी. पुढील पेमेंटपूर्वी नियमांचे पालन तपासणे आवश्यक.",
      },
      {
        id: 5,
        priority: "LOW",
        titleEn: "Monsoon Damage Assessment — Eastern Zone",
        titleMr: "मान्सून नुकसान मूल्यांकन — पूर्व विभाग",
        contextEn: "Minor retaining wall cracks reported. Engineering inspection requested to assess safety hazard.",
        contextMr: "भिंतीला किरकोळ तडे गेल्याची तक्रार. सुरक्षेचा धोका तपासण्यासाठी अभियंत्यांच्या तपासणीची विनंती.",
      },
    ],
    anomalies: [
      {
        id: 1,
        severity: "HIGH",
        titleEn: "Pothole Spike — Ward 12",
        titleMr: "खड्ड्यांच्या तक्रारीत वाढ — वॉर्ड १२",
        explanationEn: "27 unique citizen reports of deep potholes received for Ward 12 within a 4-hour window.",
        explanationMr: "४ तासांच्या कालावधीत वॉर्ड १२ मध्ये खोल खड्ड्यांच्या २७ नागरिक तक्रारी प्राप्त झाल्या.",
        detectedAtEn: "08:14 AM",
        detectedAtMr: "सकाळी ०८:१४",
      },
      {
        id: 2,
        severity: "HIGH",
        titleEn: "Repair Delay — Market Junction",
        titleMr: "रस्ता दुरुस्तीस विलंब — मार्केट जंक्शन",
        explanationEn: "Asphalt layer laying delayed by 5 hours due to equipment malfunction at contractor plant.",
        explanationMr: "कंत्राटदाराच्या प्लॅन्टमधील उपकरण बिघाडामुळे डांबरी थर टाकण्यास ५ तास विलंब झाला.",
        detectedAtEn: "08:27 AM",
        detectedAtMr: "सकाळी ०८:२७",
      },
      {
        id: 3,
        severity: "MEDIUM",
        titleEn: "Drainage Overflow — Sector 4",
        titleMr: "ड्रेनेज तुंबण्याच्या वारंवार तक्रारी — सेक्टर ४",
        explanationEn: "Sector 4 reports 8 repeated overflow complaints today. Sewer line blockage suspected.",
        explanationMr: "सेक्टर ४ मध्ये आज सांडपाणी तुंबण्याच्या ८ वारंवार तक्रारी. गटार लाईन ब्लॉक झाल्याची शक्यता.",
        detectedAtEn: "07:55 AM",
        detectedAtMr: "सकाळी ०७:५५",
      },
      {
        id: 4,
        severity: "MEDIUM",
        titleEn: "Progress Delay — Bridge Project",
        titleMr: "कामाच्या प्रगतीत विलंब — पूल प्रकल्प",
        explanationEn: "Abutment concrete pouring delayed by 48 hours. Projected project milestone delayed by 4 days.",
        explanationMr: "खांब कॉंक्रिट ओतण्यास ४८ तास विलंब. प्रकल्पाचे पुढील उद्दिष्ट ४ दिवसांनी लांबणीवर पडले.",
        detectedAtEn: "07:30 AM",
        detectedAtMr: "सकाळी ०७:३०",
      },
      {
        id: 5,
        severity: "LOW",
        titleEn: "Quality Inspection Discrepancy",
        titleMr: "गुणवत्ता तपासणीत विसंगती",
        explanationEn: "Contractor material test sheet shows minor core strength variations from road authority test.",
        explanationMr: "कंत्राटदाराच्या साहित्याची चाचणी आणि रस्ते प्राधिकरणाच्या चाचणीत किरकोळ फरक आढळला आहे.",
        detectedAtEn: "07:02 AM",
        detectedAtMr: "सकाळी ०७:०२",
      },
    ],
  },
];
